In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [2]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hridvi dubey\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\hridvi dubey\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hridvi dubey\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hridvi dubey\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\hridvi dubey\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [4]:
iris=sns.load_dataset("iris")

In [5]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

iris["species"]=le.fit_transform(iris["species"])

In [7]:
iris

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [8]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int32
dtypes: float64(4), int32(1)
memory usage: 5.4 KB

In [9]:
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [10]:
iris.duplicated().sum()

1

In [11]:
iris=iris.drop_duplicates(keep="first")

In [12]:
iris.duplicated().sum()

0

In [13]:
X=iris.drop("species",axis=1)
Y=iris["species"]

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [15]:
lg=LogisticRegression()
lg.fit(X_train,Y_train)

LogisticRegression()

In [16]:
y_pred=lg.predict(X_test)

In [17]:
y_pred

array([2, 1, 1, 2, 1, 2, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 2,
       0, 2, 2, 0, 1, 0, 1, 2])

In [18]:
lg.score(X_train,Y_train)

0.9747899159663865

In [19]:
lg.score(X_test,Y_test)

0.9333333333333333

In [20]:
print("Accuracy Score:",accuracy_score(Y_test,y_pred))

Accuracy Score: 0.9333333333333333

In [21]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.92      0.92      0.92        13
           2       0.86      0.86      0.86         7

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

In [22]:
print(confusion_matrix(Y_test,y_pred))

[[10  0  0]
 [ 0 12  1]
 [ 0  1  6]]

In [23]:
import pickle


#pickle is a python module used to convert objects into a file and load them back later

#It saves your trained model so you dont have to train it again.

In [24]:
#SAVE MODEL

with open("iris_model.pkl","wb") as f:
    pickle.dump(lg,f)

In [25]:
#LOAD MODEL 

with open("iris_model.pkl","rb") as f:
    model=pickle.load(f)

In [26]:
#Make new prediction


sample=[[1.5,2.5,2.0,1.9]]


prediction=model.predict(sample)
species_map={0:"Setosa",1:"Versicolor",2:"Virginica"}

print("Predicted Class:",species_map[prediction[0]])

Predicted Class: Setosa

C:\Users\Hridvi Dubey\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(